### ISSUE TITLE
Does there exist a paper?

### ISSUE THREAD

**Issue by hcmdgh** [joshchang1112/bert_gnn_arxiv#1]
Hello, your analysis of Multi-class Classification with fine-tuned BERT & GNN is in detail, professional and understandable. It seems to have a paper associated with the project. Could you show the paper? Or is it still in progress?

**Comment by joshchang1112** [comment]
Hi, 
the paper is still in progress, and this repository just includes one part of the experiments in our paper. Glad to hear that someone is also interested in this topic, if our paper is finished, we will share our work and the whole paper on Github. If you have any questions or suggestions, just feel free to let us know:)

**Comment by 2kjiejie** [comment]
Hi, your work looks great, and I'm also interested in it. So is there a paper published now? Really looking forward to reading it!

**Comment by zlrhhh** [comment]
Hello, Do you have a corresponding paper for this code?
